Optimise fetch_mcp
EBI-Metagenomics/mgnify-pipelines-toolkit pull request #5
Opened 2024-02-20 16:38 UTC by chrisAta

the `fetch_mcp` function in `amplicon_utils` currently looks at all the reads of a fastq file to generate MCPs. For relatively large amplicon files (think millions of reads), it isn't necessary to consider all the reads. This PR sets an arbitrary threshold (that works well in practice) of 300,000 reads after which the fetch_mcp function exits early. Related scripts that use this function were also modified, and unit tests for a big amplicon file was also made.

Also fixed the `get_read_count` function which would give inaccurate counts as the symbol `@` is used in the quality score line of fastq files. The new function extracts all of the header lines with `sed` and then counts the number of lines.

2024-02-21 10:59 UTC, mberacochea commented on mgnify_pipelines_toolkit/analysis/amplicon/assess_inflection_point_mcp.py
> +    if read_count > 300_000:
Can you create a constants file and put this value there? It's easier to track / update that way

2024-02-21 11:04 UTC, mberacochea commented on mgnify_pipelines_toolkit/analysis/amplicon/amplicon_utils.py
> +        proc_1 = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```suggestion
        zcat_pipe = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

2024-02-21 11:04 UTC, mberacochea commented on mgnify_pipelines_toolkit/analysis/amplicon/amplicon_utils.py
> +        proc_2 = subprocess.Popen(cmd, stdin=proc_1.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```suggestion
        sed_proc = subprocess.Popen(cmd, stdin=proc_1.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

2024-02-21 11:05 UTC, mberacochea commented on mgnify_pipelines_toolkit/analysis/amplicon/amplicon_utils.py
> +        proc_3 = subprocess.Popen(cmd, stdin=proc_2.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```suggestion
        wc_proc = subprocess.Popen(cmd, stdin=sed_proc.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

2024-02-21 11:11 UTC, mberacochea commented on mgnify_pipelines_toolkit/analysis/amplicon/amplicon_utils.py
> +        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```suggestion
        grep_proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

2024-02-21 11:12 UTC, mberacochea commented on mgnify_pipelines_toolkit/analysis/amplicon/amplicon_utils.py
> +        stdout, stderr = proc.communicate()
```suggestion
        stdout, stderr = grep_proc.communicate()
```

2024-02-21 11:14 UTC, mberacochea commented on mgnify_pipelines_toolkit/analysis/amplicon/amplicon_utils.py
>      read_count = int(stdout.strip())
I would add a sanity check here with `stdout.isdigit()`, just in case. Docs https://docs.python.org/3/library/stdtypes.html#str.isdigit

2024-02-21 11:15 UTC, mberacochea requested changes
Great :). I've added some minor comments

2024-02-21 14:32 UTC, chrisAta commented
Done @mberacochea! I moved a few more things into constants and also updated the README

2024-02-21 21:45 UTC, mberacochea approved these changes
Excellent, thanks @chrisAta . I've added one more test for the isdigit change, also as an example.

There are 2 things we need to add (not on this PR, in the following days)
- precommits
- linters

2024-02-21 21:47 UTC, mberacochea commented
One comment: "Also fixed the get_read_count function which would give inaccurate counts as the symbol @ is used in the quality score line of fastq files. The new function extracts all of the header lines with sed and then counts the number of lines.". For fastq you can also count the numbers of lines and divide by 4 (each seq will have 4 lines)

2024-02-22 08:56 UTC, merged

2024-02-22 09:29 UTC, KateSakharova reviewed
:shipit: