Changes to support assigning taxonomy to ASV using MAPseq output
EBI-Metagenomics/mgnify-pipelines-toolkit pull request #6
Opened 2024-04-23 09:43 UTC by chrisAta

Recently changed the tool used in V6 amplicon for assigning taxonomy to ASVs from DADA2 to MAPseq. This change has necessitated adding a conversion script (mapseq2asvtable.py) and updating the make_asv_count_table.py script.

2024-04-23 14:32 UTC, mberacochea commented on mgnify_pipelines_toolkit/analysis/amplicon/make_asv_count_table.py
> +                tax_assignment += f"{sk}"
```suggestion
                tax_assignment += sk
```

2024-04-23 14:44 UTC, mberacochea commented on mgnify_pipelines_toolkit/analysis/amplicon/make_asv_count_table.py
> +                tax_assignment += f"{d}"
```suggestion
                tax_assignment += d
```

2024-04-23 14:48 UTC, mberacochea requested changes
It looks good to me, I didn't do an extensive review but the code looks alright to me.
I added some minor comments

2024-04-23 15:50 UTC, chrisAta commented
> It looks good to me, I didn't do an extensive review but the code looks alright to me. I added some minor comments

thank you! changes done

2024-04-26 10:44 UTC, mberacochea approved these changes
:shipit:

2024-04-26 11:31 UTC, merged