V6 qc additions
EBI-Metagenomics/mgnify-pipelines-toolkit pull request #8
Opened 2024-08-06 15:05 UTC by chrisAta

2024-08-07 11:03 UTC, KateSakharova requested changes
Thanks Chris!
Only python quibbles from me, sorry

2024-08-07 11:03 UTC, KateSakharova commented on mgnify_pipelines_toolkit/analysis/shared/library_strategy_check.py
> +
empty line, maybe add shebang here?

2024-08-07 11:03 UTC, KateSakharova commented on mgnify_pipelines_toolkit/analysis/shared/library_strategy_check.py
> +    return INPUT, SAMPLE, OUTPUT
the same comments about uppercase

2024-08-08 09:23 UTC, chrisAta commented on mgnify_pipelines_toolkit/analysis/amplicon/classify_var_regions.py
> +            if new_value == []:
Didn't know this works! very cool

2024-08-08 09:24 UTC, chrisAta commented on mgnify_pipelines_toolkit/analysis/shared/fastq_suffix_header_check.py
> +    if len(reads_with_err) != 0:
Cool that this works but I think this one I will keep as it is, it's easier to understand if it's this explicit IMO

2024-08-08 10:39 UTC, KateSakharova approved these changes

2024-08-08 10:42 UTC, merged